"""Self-improving tracking paths: BLE path-loss learning from
camera-confirmed distances, adaptive per-sensor trust, camera-measured
device positions, tomography re-baselining."""

import math
import random

import pytest

from hometwin.config import AppConfig
from hometwin.devicetags import DeviceTagSolver
from hometwin.fusion import FusionEngine
from hometwin.items import Item, ItemRegistry
from hometwin.observations import PositionObservation
from hometwin.sensors.ble import BLEScannerSensor, PathLossModel, RSSISource
from hometwin.sensors.mock import ScriptedSensor
from hometwin.sensors.tomography import TomographySensor
from hometwin.tracker import Tracker
from hometwin.world import World, Zone


# --- online BLE path-loss learning ----------------------------------------------

class EnvSource(RSSISource):
    """RSSI generated by the REAL environment model at the item's true spot."""

    def __init__(self, scanner_pos, env_model, holder, noise=0.5, seed=3):
        self.pos, self.env, self.holder = scanner_pos, env_model, holder
        self.rng = random.Random(seed)
        self.noise = noise

    def readings(self):
        d = math.dist(self.pos, self.holder["pos"])
        return [("AA:11:22:33:44:55", self.env.range_to_rssi(d) + self.rng.gauss(0, self.noise))]


class SimClock:
    def __init__(self):
        self.now = 1000.0

    def advance(self, dt=0.5):
        self.now += dt

    def __call__(self):
        return self.now


def make_learning_tracker(camera_confirmed=True):
    env = PathLossModel(tx_power=-63.0, exponent=3.2)   # the real walls
    items = ItemRegistry()
    items.add(Item("keys", "Keys", tag_ids=["aruco:7", "ble:AA:11:22:33:44:55"]))
    world = World([Zone("room", (0, 0, 0), (8, 4, 2.6))])
    holder = {"pos": (1.0, 2.0, 0.9)}
    scanner = BLEScannerSensor("ble-1", position=(0.0, 0.0, 2.2))  # factory model
    scanner.source = EnvSource(scanner.position, env, holder)
    cam = ScriptedSensor("cam")
    tracker = Tracker(AppConfig(world=world, items=items, sensors=[cam, scanner]))
    clock = SimClock()
    scanner.clock = clock

    rng = random.Random(11)
    for step in range(220):
        clock.advance()
        # the item wanders so distances span the room (1..7 m)
        x = 1.0 + 6.0 * (0.5 + 0.5 * math.sin(step / 25.0))
        holder["pos"] = (x, 2.0, 0.9)
        if camera_confirmed:
            cam.push([PositionObservation(
                sensor_id="cam", timestamp=clock.now, item_id="aruco:7",
                position=tuple(p + rng.gauss(0, 0.03) for p in holder["pos"]),
                sigma_m=0.05,
            )])
        tracker.step()
    return tracker, scanner, env


def test_path_loss_learns_environment_online():
    tracker, scanner, env = make_learning_tracker()
    status = tracker.learning_status()
    assert status and status[0]["refits"] >= 3
    assert scanner.model.exponent == pytest.approx(3.2, abs=0.25)
    assert scanner.model.tx_power == pytest.approx(-63.0, abs=2.0)
    # ranging error at 3 m improved vs the factory model it started with
    rssi = env.range_to_rssi(3.0)
    assert abs(scanner.model.rssi_to_range(rssi) - 3.0) < abs(
        PathLossModel().rssi_to_range(rssi) - 3.0
    )


def test_no_learning_without_camera_confirmation():
    """Range-only tracks must never teach the scanner (feedback loop)."""
    tracker, scanner, _ = make_learning_tracker(camera_confirmed=False)
    status = tracker.learning_status()
    assert not status or status[0]["samples"] == 0
    assert scanner.model.exponent == pytest.approx(2.7, abs=1e-9)


# --- adaptive per-sensor trust ---------------------------------------------------

def run_two_sensor_fusion(adaptive):
    items = ItemRegistry()
    items.add(Item("keys", "Keys", tag_ids=["aruco:7"]))
    eng = FusionEngine(items, World([Zone("room", (0, 0, 0), (8, 4, 2.6))]))
    eng.adaptive_trust = adaptive
    rng = random.Random(5)
    true_pos = (3.0, 2.0, 0.9)
    err = None
    for i in range(200):
        t = float(i)
        eng.ingest(PositionObservation(  # honest sensor: claims what it is
            sensor_id="good", timestamp=t, item_id="aruco:7",
            position=tuple(p + rng.gauss(0, 0.1) for p in true_pos), sigma_m=0.1))
        eng.ingest(PositionObservation(  # liar: claims 0.05, delivers 0.5
            sensor_id="liar", timestamp=t + 0.5, item_id="aruco:7",
            position=tuple(p + rng.gauss(0, 0.5) for p in true_pos), sigma_m=0.05))
        err = math.dist(eng.tracks["keys"].position, true_pos)
    return eng, err


def test_adaptive_trust_demotes_overconfident_sensor():
    eng_on, err_on = run_two_sensor_fusion(adaptive=True)
    _, err_off = run_two_sensor_fusion(adaptive=False)
    assert eng_on.trust("liar") > 5.0   # ~matches its 10x sigma understatement
    assert eng_on.trust("good") < 2.5   # honest sensor stays trusted
    assert err_on < err_off * 0.5       # fusion got measurably better


# --- camera-measured device positions --------------------------------------------

def test_device_tag_triangulation_corrects_scanner_position():
    true_pos = (4.0, 0.1, 2.0)
    scanner = BLEScannerSensor("ble-1", position=(3.7, 0.1, 2.0))  # surveyed 0.3 m off
    solver = DeviceTagSolver()
    solver.register("aruco:50", scanner, auto_correct=True)
    cams = [(0.0, 2.0, 2.2), (8.0, 3.5, 2.2)]
    for i in range(30):
        for origin in cams:
            d = [true_pos[k] - origin[k] for k in range(3)]
            n = math.sqrt(sum(x * x for x in d))
            assert solver.observe_ray(
                "aruco:50", origin, tuple(x / n for x in d), float(i))
    assert math.dist(scanner.position, true_pos) < 0.03
    snap = solver.snapshot()[0]
    assert snap["position_residual_m"] == pytest.approx(0.3, abs=0.05)


def test_device_tag_single_viewpoint_never_corrects():
    scanner = BLEScannerSensor("ble-1", position=(3.7, 0.1, 2.0))
    solver = DeviceTagSolver()
    solver.register("aruco:50", scanner, auto_correct=True)
    for i in range(20):
        assert solver.observe_ray("aruco:50", (0, 2, 2.2), (0.9, -0.3, 0.05), float(i))
    assert scanner.position == (3.7, 0.1, 2.0)  # no depth from one camera
    assert solver.snapshot()[0]["estimate"] is None
    assert not solver.observe_ray("aruco:99", (0, 0, 0), (1, 0, 0), 1.0)


def test_device_tag_correction_clamped():
    scanner = BLEScannerSensor("ble-1", position=(0.0, 0.0, 2.0))
    solver = DeviceTagSolver()
    solver.register("aruco:50", scanner, auto_correct=True)
    bogus = (4.0, 0.0, 2.0)  # 4 m away: impossible survey error
    for i in range(40):
        for origin in ((0.0, 3.0, 2.2), (8.0, 3.0, 2.2)):
            d = [bogus[k] - origin[k] for k in range(3)]
            n = math.sqrt(sum(x * x for x in d))
            solver.observe_ray("aruco:50", origin, tuple(x / n for x in d), float(i))
    assert math.dist(scanner.position, (0.0, 0.0, 2.0)) <= 1.0 + 1e-6  # clamped


# --- tomography auto re-baseline --------------------------------------------------

def square_mesh():
    return {"n0": (0.0, 0.0), "n1": (4.0, 0.0), "n2": (4.0, 4.0), "n3": (0.0, 4.0)}


class StaticLinks:
    def __init__(self, nodes, rss_map):
        self.nodes, self.rss_map = nodes, rss_map

    def readings(self):
        names = sorted(self.nodes)
        out = []
        for i, a in enumerate(names):
            for b in names[i + 1:]:
                out.append((a, b, self.rss_map.get((a, b), -50.0)))
        return out


def test_furniture_move_absorbed_after_persistence_window():
    nodes = square_mesh()
    sensor = TomographySensor("rti", nodes=nodes, bounds=(0, 0, 4, 4),
                              rebaseline_after_s=600.0)
    clock = SimClock()
    sensor.clock = clock
    rss = {}
    sensor.source = StaticLinks(nodes, rss)
    sensor.calibrate(sensor.source.readings())  # empty-room baselines at -50

    rss[("n0", "n2")] = -58.0  # bookshelf moved onto the diagonal: permanent
    clock.advance(1.0)
    assert len(sensor.poll()) == 1  # initially looks like presence
    clock.advance(700.0)  # persists past the window
    sensor.poll()  # absorbs the new normal
    assert sensor.rebaselined_links == 1
    clock.advance(1.0)
    assert sensor.poll() == []  # ghost gone

    # a person on the same link is detected again against the NEW baseline
    rss[("n0", "n2")] = -66.0
    clock.advance(1.0)
    assert len(sensor.poll()) == 1


def test_slow_drift_tracked_without_phantoms():
    nodes = square_mesh()
    sensor = TomographySensor("rti", nodes=nodes, bounds=(0, 0, 4, 4))
    clock = SimClock()
    sensor.clock = clock
    rss = {}
    sensor.source = StaticLinks(nodes, rss)
    sensor.calibrate(sensor.source.readings())

    # humidity/temperature drift: every link slowly sinks 4 dB — sub-threshold
    # per step, and the baseline follows so it never accumulates
    for step in range(200):
        for i, a in enumerate(sorted(nodes)):
            for b in sorted(nodes)[i + 1:]:
                rss[(a, b)] = -50.0 - 4.0 * step / 200.0
        clock.advance(5.0)
        assert sensor.poll() == []
